name: gestore_spesa
description: "Inserisci la dieta e genera la spesa settimanale."
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
