name: dietando
description: "Insert your diet and get your weekly shopping list."
publish_to: 'none'
version: 1.0.0+26

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  intl: ^0.20.2
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  web: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  
  # Opzionale: per piattaforme specifiche
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
  linux:
    generate: true
    image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#7692FF"
  image: assets/icon/app_icon.png
  android_screen_orientation: portrait
  ios_content_mode: center
  web: true
  web_image_mode: center


